spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: YksnNTyNwLi7C4s3
    #password: 745458741
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
        # 单文件大小限制
      max-file-size: 10MB
        # 总上传大小限制
      max-request-size: 10MB

server:
  port: 8000
logging:
  level:
    root: error


#封装yml
datasource:
  url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  driver: com.mysql.cj.jdbc.Driver
  username: root
  password: YksnNTyNwLi7C4s3
  #password: 745458741
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      #table-prefix: t_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
upload:
  # 上传的图片保存路径（可自定义）
  path:  E:/learnJava/learnSpringboot/project/src/main/java/com/project/upload/
