spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 745458741
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8090
logging:
  level:
    root: error


#封装yml
datasource:
  url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  driver: com.mysql.cj.jdbc.Driver
  username: root
  password: 745458741
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      #table-prefix: t_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dr